/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import static config.config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Anton
 */
public class userPage extends javax.swing.JInternalFrame {

    private int loggedInUserID; // store the logged-in user id

public userPage(int userId) {
    initComponents();
    this.loggedInUserID = userId;
    loadUserProfile(); // load the profile automatically
}
    public void loadUserProfile() {
    String sql = "SELECT a_id, name, email, pass, type, status FROM tbl_Accounts WHERE a_id = ?";

    try (Connection con = connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, loggedInUserID);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            userID.setText("ID: " + rs.getInt("a_id"));
            userName.setText("Name: " + rs.getString("name"));
            userEmail.setText("Email: " + rs.getString("email"));
            UserStatus.setText("Status: " + rs.getString("status"));
            // Optional: you can also show type if you want
            // userType.setText("Type: " + rs.getString("type"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load profile: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        UserStatus = new javax.swing.JLabel();
        userID = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(247, 242, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 70));

        jPanel2.setBackground(new java.awt.Color(255, 248, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName.setText("name:");
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 510, 40));

        userEmail.setText("Email:");
        jPanel2.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 510, 40));

        UserStatus.setText("Status:");
        jPanel2.add(UserStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 510, 40));

        userID.setText("ID:");
        jPanel2.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 510, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userID;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
