
package main;

import config.config;
import java.awt.Color;
import javax.swing.JOptionPane;

public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    public registerForm() {
        initComponents();
    }
    Color hover = new Color(143,177,138);
    Color Buttons = new Color(167,196,160);
    
    private boolean isValidInput() {
    String name = fullname.getText().trim();
    String emailText = email.getText().trim();
    String password = pass.getText().trim();

    config con = new config();

    // Empty fields
    if (name.isEmpty() || emailText.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required.");
        return false;
    }

    // Name validation
    if (!name.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(null, "Full name must contain letters only.");
        return false;
    }

    // Email format
    if (!emailText.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        JOptionPane.showMessageDialog(null, "Invalid email format.");
        return false;
    }

    // 🚫 Duplicate email check (HERE)
    if (con.isEmailExist(emailText)) {
        JOptionPane.showMessageDialog(null, "Email already exists.");
        return false;
    }

    // Password length
    if (password.length() < 6) {
        JOptionPane.showMessageDialog(null, "Password must be at least 6 characters.");
        return false;
    }

    return true; // ✅ everything passed
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        logopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registerbox = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Back = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        registerbtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        fillupForm = new javax.swing.JPanel();
        SignIn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logopanel.setBackground(new java.awt.Color(232, 214, 201));
        logopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bigPic.png"))); // NOI18N
        logopanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        getContentPane().add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 311, 420));

        registerbox.setBackground(new java.awt.Color(247, 242, 236));
        registerbox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Create Account");
        registerbox.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 60));

        Back.setBackground(new java.awt.Color(167, 196, 160));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Back");
        Back.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 110, 20));

        registerbox.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, 40));

        fullname.setBackground(new java.awt.Color(255, 246, 240));
        fullname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fullname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fullname", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        registerbox.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 250, 50));

        email.setBackground(new java.awt.Color(255, 246, 240));
        email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        registerbox.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, 50));

        pass.setBackground(new java.awt.Color(255, 246, 240));
        pass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CreatePassword", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        registerbox.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 250, 50));

        registerbtn.setBackground(new java.awt.Color(167, 196, 160));
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerbtnMouseExited(evt);
            }
        });
        registerbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Register");
        registerbtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 9, 110, 20));

        registerbox.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 40));

        fillupForm.setBackground(new java.awt.Color(255, 248, 242));
        fillupForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignIn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn.setText("Click here to Sign In");
        SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignInMouseExited(evt);
            }
        });
        fillupForm.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Already have an account?");
        fillupForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 20));

        registerbox.add(fillupForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 370, 310));

        getContentPane().add(registerbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 450, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        landingForm lf = new landingForm();
        lf.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(hover);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(Buttons);
    }//GEN-LAST:event_BackMouseExited

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
        if(!isValidInput()){
            return;
        }
        config con = new config();
        
        String sql = "INSERT INTO tbl_Accounts (name, email, pass, type, status) VALUES (?, ?, ?, ?, ?)";
        con.addRecord(sql, fullname.getText(), email.getText(), pass.getText(), "User", "Pending");
        JOptionPane.showMessageDialog(null, "RECORD ADDED!");
    }//GEN-LAST:event_registerbtnMouseClicked

    private void registerbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseEntered
        registerbtn.setBackground(hover);
    }//GEN-LAST:event_registerbtnMouseEntered

    private void registerbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseExited
        registerbtn.setBackground(Buttons);
    }//GEN-LAST:event_registerbtnMouseExited

    private void SignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseEntered
        SignIn.setForeground(new java.awt.Color(0, 153, 255)); // Hover text color (blue)
        SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SignInMouseEntered

    private void SignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseExited
        SignIn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_SignInMouseExited

    private void SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseClicked
        loginForm logf = new loginForm();
        logf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JLabel SignIn;
    private javax.swing.JTextField email;
    private javax.swing.JPanel fillupForm;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel logopanel;
    private javax.swing.JTextField pass;
    private javax.swing.JPanel registerbox;
    private javax.swing.JPanel registerbtn;
    // End of variables declaration//GEN-END:variables
}
