/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import config.config;
import internalPages.*;

/**
 *
 * @author Anton
 */
public class userDashboard extends javax.swing.JFrame {

    private int userId;
    private String fullName;
    private String email;
    
    public userDashboard() {
        initComponents();
    }

    public userDashboard(int userId, String fullName, String email) {
    initComponents();

    this.userId = userId;
    this.fullName = fullName;
    this.email = email;

    // Example: show user info in header
    jLabel5.setText("Welcome, " + fullName);

    loadUserProfile();
}

    public void loadUserProfile() {

    String sql = "SELECT name, email, pass, type, status FROM tbl_Accounts WHERE a_id = ?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, userId);
        ResultSet rs = pst.executeQuery();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to load profile: " + e.getMessage());
    }
}

    Color hover = new Color(143,177,138);
    Color Buttons = new Color(227,235,221);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userProfile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        posts = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        userDesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 248, 242));
        jPanel1.setLayout(null);

        Navbar.setBackground(new java.awt.Color(227, 235, 221));
        Navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(227, 235, 221));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 20));

        Navbar.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 40));

        userProfile.setBackground(new java.awt.Color(227, 235, 221));
        userProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userProfileMouseExited(evt);
            }
        });
        userProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Profile");
        userProfile.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 20));

        Navbar.add(userProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 40));

        posts.setBackground(new java.awt.Color(227, 235, 221));
        posts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                postsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                postsMouseExited(evt);
            }
        });
        posts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Posts");
        posts.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 20));

        Navbar.add(posts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 40));

        logout.setBackground(new java.awt.Color(227, 235, 221));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Logout");
        logout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 20));

        Navbar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 40));

        jPanel1.add(Navbar);
        Navbar.setBounds(0, 0, 210, 480);

        Header.setBackground(new java.awt.Color(247, 242, 236));
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(247, 242, 236), new java.awt.Color(247, 242, 236), null, null));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Dashboard");
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 550, 40));

        jPanel1.add(Header);
        Header.setBounds(210, 0, 780, 60);

        userDesktop.setBackground(new java.awt.Color(247, 242, 236));

        javax.swing.GroupLayout userDesktopLayout = new javax.swing.GroupLayout(userDesktop);
        userDesktop.setLayout(userDesktopLayout);
        userDesktopLayout.setHorizontalGroup(
            userDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        userDesktopLayout.setVerticalGroup(
            userDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(userDesktop);
        userDesktop.setBounds(210, 60, 770, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(hover);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(Buttons);
    }//GEN-LAST:event_homeMouseExited

    private void userProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProfileMouseEntered
        userProfile.setBackground(hover);
    }//GEN-LAST:event_userProfileMouseEntered

    private void userProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProfileMouseExited
        userProfile.setBackground(Buttons);
    }//GEN-LAST:event_userProfileMouseExited

    private void postsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postsMouseEntered
        posts.setBackground(hover);
    }//GEN-LAST:event_postsMouseEntered

    private void postsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postsMouseExited
        posts.setBackground(Buttons);
    }//GEN-LAST:event_postsMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(hover);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(Buttons);
    }//GEN-LAST:event_logoutMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        
        
    }//GEN-LAST:event_homeMouseClicked

    private void userProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProfileMouseClicked
        userPage up = new userPage(this.userId);
        userDesktop.add(up).setVisible(true);
    }//GEN-LAST:event_userProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel posts;
    private javax.swing.JDesktopPane userDesktop;
    private javax.swing.JPanel userProfile;
    // End of variables declaration//GEN-END:variables
}
